dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.4
      env: TOXENV=py34-flask010
    - python: 3.5
      env: TOXENV=py35-flask010
    - python: 3.6
      env: TOXENV=py36-flask010
    - python: 3.7
      env: TOXENV=py37-flask010
    - python: 3.8-dev
      env: TOXENV=py38-flask010
    - python: 3.4
      env: TOXENV=py34-flask011
    - python: 3.5
      env: TOXENV=py35-flask011
    - python: 3.6
      env: TOXENV=py36-flask011
    - python: 3.7
      env: TOXENV=py37-flask011
    - python: 3.8-dev
      env: TOXENV=py38-flask011
    - python: 3.4
      env: TOXENV=py34-flask012
    - python: 3.5
      env: TOXENV=py35-flask012
    - python: 3.6
      env: TOXENV=py36-flask012
    - python: 3.7
      env: TOXENV=py37-flask012
    - python: 3.8-dev
      env: TOXENV=py38-flask012
    - python: 3.4
      env: TOXENV=py34-flask10
    - python: 3.5
      env: TOXENV=py35-flask10
    - python: 3.6
      env: TOXENV=py36-flask10
    - python: 3.7
      env: TOXENV=py37-flask10
    - python: 3.8-dev
      env: TOXENV=py38-flask10
    - python: 3.4
      env: TOXENV=py34-flask11
    - python: 3.5
      env: TOXENV=py35-flask11
    - python: 3.6
      env: TOXENV=py36-flask11
    - python: 3.7
      env: TOXENV=py37-flask11
    - python: 3.8-dev
      env: TOXENV=py38-flask11
  allow_failures:
    - python: 3.4
      env: TOXENV=py34-flaskmaster
    - python: 3.5
      env: TOXENV=py35-flaskmaster
    - python: 3.6
      env: TOXENV=py36-flaskmaster
    - python: 3.7
      env: TOXENV=py37-flaskmaster
    - python: 3.8-dev
      env: TOXENV=py38-flaskmaster

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov
